### ISSUE TITLE
Action not defined

### ISSUE THREAD

**Issue by shrenikp** [andywer/laravel-js-localization#10] opened 2015-04-07 16:38 UTC
Hey,
      am getting this after installation. Know what the issue is? 
http://screencloud.net/v/Dq5n

**Comment by andywer** [comment] 2015-04-07 16:59
Hi,
maybe you forgot to load the service provider in your config/app.php?

Cheers,
Andy

**Comment by shrenikp** [comment] 2015-04-07 17:08
Hey,
It does exist. 
http://screencloud.net/v/ymM8

Shrenik

**Comment by shrenikp** [comment] 2015-04-07 17:43
Can't get it working for the life of me. 
The service provider is there in providers array in config/app.php .
I have required the laravel 5 version of the package. Ran composer install, and dump-autoload multiple times. 
Also did run the artisan command, no errors there, it told me it has cleared the messages cache.
Happens when I include and yield from the view.  Please help.

**Comment by andywer** [comment] 2015-04-07 18:14
Yeah, I'm just coming home. Give me some time to have a look at it and I will let you know.

**Comment by shrenikp** [comment] 2015-04-07 18:27
Thanks a bunch,just to let you know the service provider is being loaded fine cause if I echo out in foo in the register function of jsLocalizationServiceProvider, it does it echo it.

**Comment by andywer** [comment] 2015-04-07 19:43
Did you use the right branch matching your Laravel version when requiring the package?

**Comment by shrenikp** [comment] 2015-04-08 09:44
Yes I did. I used dev-laravel-5. My Laravel version is 5.0.27

**Comment by andywer** [comment] 2015-04-08 11:36
Can you please try the following modification?

in vendor/andywer/js-localization/src/routes.php change `Route::get('/js-localization/messages', 'JsLocalizationController@createJsMessages');` to `Route::get('/js-localization/messages', '\JsLocalizationController@createJsMessages');`.

**Comment by andywer** [comment] 2015-04-08 11:37
Or try adding `use \JsLocalizationController;` to the top of the routes.php

**Comment by shrenikp** [comment] 2015-04-08 11:41
Tried both each at a time and together. Still the same error.

**Comment by andywer** [comment] 2015-04-08 11:46
I think the problem is that your app is looking for a App\Http\Controllers\JsLocalizationController instead of a \JsLocalizationController. But I am not yet sure why it does not let you change this behavious or why I do not encounter the same problem.

I will try writing a fix this evening.

**Comment by shrenikp** [comment] 2015-04-08 11:47
Hmm, alright :)

**Comment by andywer** [comment] 2015-04-08 16:27
Another thought: Could you try wrapping the routes in the package's routes.php in

```
Route::group(['namespace' => '\'], function()
{
    // the routes go here
});
```
?

(try `'namespace' => ''` if this does not work)

I can easily write a clean solution if this actually solves the problem.

**Comment by shrenikp** [comment] 2015-04-08 16:51
http://screencloud.net/v/ued3

Tried both, unfortunately the same :(

**Comment by shrenikp** [comment] 2015-04-08 17:10
Ok so I did the following
1. In routes group, I did http://screencloud.net/v/8iaz i.e add "JsLocalization" to namespace. and then
2. In head.blade.php, src="{{ action('\JsLocalization\JsLocalizationController@createJsMessages') }}">
3. It shows me this output instead of the error
http://screencloud.net/v/uUIv 
but in console it fails to fetch the http://shrenik.con-dev.app/js-localization/messages with 500 internal error.
The logs show this error: 
[2015-04-08 17:03:55] local.ERROR: exception 'ReflectionException' with message 'Class JsLocalization\JsLocalizationController does not exist' in /usr/share/nginx/html/con-dev/sub/vendor/laravel/framework/src/Illuminate/Container/Container.php:776

**Comment by andywer** [comment] 2015-04-08 17:50
Ok, I am pretty certain I have got a working quick-fix for now:

Do not touch your namespace "JsLocalization" fix.
Move `src/controllers/JsLocalizationController` to `src/JsLocalization/JsLocalizationController`.
Run `php artisan dump-autoload`.

**Comment by shrenikp** [comment] 2015-04-09 09:51
Nope, still the same. :(

**Comment by andywer** [comment] 2015-04-09 10:38
Ok, I will write a fix (this evening, hopefully). I tell you when I am ready, so you can require the fix and test if it works.

**Comment by shrenikp** [comment] 2015-04-09 10:41
Alright cool :)

**Comment by andywer** [comment] 2015-04-09 19:16
Please require `"andywer/js-localization": "dev-develop"` in your `composer.json` and run a `php artisan dump-autoload`.

Tell me if it works :)

**Comment by shrenikp** [comment] 2015-04-10 11:05
It works :) Will you be merging the branch or should I keep "dev-develop" for now?

**Comment by andywer** [comment] 2015-04-10 11:20
Already merged into `laravel-5` ;)

Thank you!

**Closed by andywer** 2015-04-10 11:20 UTC

**Comment by shrenikp** [comment] 2015-04-10 11:26
Great, I shall pull that. Thanks a bunch.

**Comment by Wmas** [comment] 2015-04-10 11:28
Thank you very much for your effort making this package to work with Laravel 5
