### ISSUE TITLE
Replacement parameters are case sensitive

### ISSUE THREAD

**Issue by BARNZ** [andywer/laravel-js-localization#39] opened 2017-05-23 14:07 UTC
In laravel docs you can change the casing of lang params to change how they are displayed in the resulting string:

> https://laravel.com/docs/5.4/localization#replacing-parameters-in-translation-strings
>
>![image](https://cloud.githubusercontent.com/assets/2202345/26358387/85f7899a-4026-11e7-95ee-f92bcded9527.png)

When I use the associated `trans` function in js I instead get the following result:
![image](https://cloud.githubusercontent.com/assets/2202345/26358251/08c7d998-4026-11e7-8d60-41dbb2ce64a0.png)

My `:What` parameter has first character capitalized, so the 2nd example doesn't work as expected.

That aside, great library btw!

**Comment by andywer** [comment] 2017-05-24 07:09
Hey @BARNZ.

That seems right, thanks! Feel free to open a PR if you need a fix quickly (need to edit [localization.js](https://github.com/andywer/laravel-js-localization/blob/laravel-5/resources/js/localization.js)).

**Comment by andywer** [comment] 2018-04-16 15:27
@carestad Would be cool if you could tell us if the issue is fixed now.

(Should have been fixed by #47.)

**Comment by carestad** [comment] 2018-04-16 18:34
Maybe you meant to tag @BARNZ, @andywer? Works well for me.

I based the JS code on how [Laravel does this in PHP](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Translation/Translator.php#L258).

**Comment by andywer** [comment] 2018-04-17 04:19
Sounds good. Let's close it :)

**Closed as completed by andywer** 2018-04-17 04:19 UTC
